### PR TITLE
Fabo/2687 fix proposal creation

### LINKED ISSUE #2687: Submitting proposal errors
**Describe the bug**
Proposals are not being submitted but rather erroring out.

**To Reproduce**
From the Governance tab click Create Proposal.
Fill in dummy information
Click Next
Click Next
Enter password
Click Submit (This is where the error occurs)
     Error message: "Submitting proposal failed: Cannot read property 'value' of undefined".

**Expected behavior**
There to be no error message but rather the proposal to be submitted.

**Screenshots**
Screen Shot 2019-06-06 at 12 50 50 PM

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2687 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by colw** [comment]
Should `state` also be supplied to `submitProposal`?

I don't think `latestId` is retrieved, so the optimistic update won't work.

**Comment by faboweb** [comment]
Nice catch!

**Comment by colw** [comment]
Awesome 👍 

I think while we're here we should rename that `state` at the top (line 25) to `initialState`.

**Comment by thebkr7** [comment]
I get an error when trying to deposit to an existing proposal with this though. It may be a separate issue though. Error: "Depositing failed: Cannot read property 'map' of undefined."

image

**Comment by faboweb** [comment]
> I think while we're here we should rename that state at the top (line 25) to initialState.

great idea

**Comment by faboweb** [comment]
> I get an error when trying to deposit to an existing proposal with this though. It may be a separate issue though. Error: "Depositing failed: Cannot read property 'map' of undefined."

might be a similar issue

**Pull request merged**
