### PR TITLE
Fabo/remove service worker

### PR DESCRIPTION
**Pull request by faboweb**
Removes the service worker completely to avoid chunk errors

### CODE REVIEW

**Comment by Bitcoinera** [comment]
@iambeone Did you test the chunks thing and confirmed this is fixing it?

**Comment by Bitcoinera** [comment]
I followed all the steps in our Lunie Weekly document to reproduce the chunks error but ultimately couldn't... in the normal develop branch.

I still think this is a good idea to merge, since the service worker doesn't seem to be anything at all

**Comment by iambeone** [comment]
Yap, i have checked and it works for me

**Comment by jbibla** [comment]
> The networks icons are squares!

this is fixed already somewhere 😄

**Pull request merged**
