### PR TITLE
Jordan/mobile

### LINKED ISSUE #96: mobile menu
since this is an electron app (and not a mobile app yet) it feels strange to me that our sidebar disappears into the hamburger menu.

i would propose we keep the sidebar visible at all times on desktop. perhaps it can be less wide.

@nylira

### LINKED ISSUE #2766: mobile fixes for session flow

### LINKED ISSUE #2771: UI: Delegate and Undelegate buttons spacing
**Describe the bug**
Delegate and Undelegate buttons do not appear with spacing. The buttons in ValidatorPage are touching rather than having space between them.

image

### PR DESCRIPTION
**Pull request by jbibla**
Closes #2766 
Closes #2771 

**Description:**

- bunch of mobile improvements
- scrolling and sizing fixes for mobile
- still lots to improve 😅 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
there is a failing test that has something to do with `$emit` - can investigate again tomorrow - probably a really easy fix.

**Comment by jbibla** [comment]
showing all values in balance header again
Screen Shot 2019-06-25 at 1 04 27 AM

mobile-friendly welcome screen
Screen Shot 2019-06-25 at 1 02 47 AM

big ol' button
Screen Shot 2019-06-25 at 1 01 24 AM

forms are spaced out a bit better
Screen Shot 2019-06-25 at 1 01 14 AM

**Comment by faboweb** [comment]
Pretty cool. The organization of the values in the header looks a bit chaotic imo. It also doesn't scale that well on medium sized screens:
image

**Comment by faboweb** [comment]
> there is a failing test that has something to do with $emit - i just skipped it for now. would be curious to know if anyone knows what the deal is.

See my commits

**Comment by jbibla** [comment]
thank you @faboweb - i tried that yesterday but put the brackets in the wrong place 🤦‍♂

**Comment by jbibla** [comment]
> Pretty cool. 

DANKE!

> The organization of the values in the header looks a bit chaotic imo. 

noted. i have an idea.

> It also doesn't scale that well on medium sized screens:

yeah, i'll fix this.

**Pull request merged**
