### PR TITLE
Ana/redenom DOT the quick way

### LINKED ISSUE #4679: DOT redenomination
Checklist from Web 3: 

Review the timeline and note the key block numbers:
- 1,205,128: Transfers enabled
- 1,248,328: Redenomination
- Prepare to change the token decimals value from 12 to 10 when redenomination occurs.

Does your project display the DOT symbol or plan to prior to redenomination?

YES: Change “DOT” to “DOT (old)” immediately. After redenomination, change to “New DOT”.

NO: After redenomination, display the DOT token as “New DOT”.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4679 
**Description:**

Simply rename the img file for DOT (stakingDenom and viewDenom have been renamed in DB)

Will now open a new PR doing this in a better way (add img path to coinLookup)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f351aa9e8987ccfafacd123--lunieio.netlify.app

**Comment by jbibla** [comment]
so when we release this we'll have to update the denom in the db as well, right?

**Comment by jbibla** [comment]
this should probably be merged into master

**Comment by Bitcoinera** [comment]
> so when we release this we'll have to update the denom in the db as well, right?

Yes, true. In Production DB, both network (stakingDenom) and coinLookup (viewDenom)

**Comment by Bitcoinera** [comment]
> this should probably be merged into master

@faboweb ?

**Comment by Bitcoinera** [comment]
Let's merge! :fire:

**Comment by faboweb** [comment]
ended up on develop

**Comment by Bitcoinera** [comment]
> ended up on develop

But it is OK, then we release, or what am I missing?

**Pull request merged**
