### PR TITLE
Mario/2965 set max button pending changes

### LINKED ISSUE #2965: Set Max button pending changes
**Describe the bug**

- Set Max button style must be secondary.
- Warning message must be shown if we enter the max amount manually, currently only shows when user click on Set Max button.

**To Reproduce**

1. Click on Send button
2. Click on Set Max button, message is shown
3. Cut & paste the input value and the message disappear

**Expected behavior**

Warning message must be shown in both cases.

### PR DESCRIPTION
**Pull request by mariopino**
Closes #2965

**Description:**

- Change Set Max button style to secondary.
- Fixed bug in warning message in send and delegate modals: Warning message is shown if we enter the max amount manually.
- Unify denomination input suffix in send, delegate and undelegate modals.
- Cleanup duplicate code in TmBtn component.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by mariopino** [comment]
> When entering the values manually on the delegation modal it doesn't show the message.
> The note about no more tokens to pay for fees pushes everything else around. Is there a way to fi that?

Fixed!

**Comment by faboweb** [comment]
Probably needs some margin:
image

**Comment by mariopino** [comment]
> Probably needs some margin:
> image

Yep, It's not finished yet, also color must be warning/yellow.

**Comment by mariopino** [comment]
image

**Comment by faboweb** [comment]
Sweet! Thank you.

**Pull request merged**
