### PR TITLE
WIP Fabo/add back button mobile

### LINKED ISSUE #3162: Add close button to mobile menu
**Describe the bug**

Currently a user can only close the mobile menu by clicking on a list item. Which he might not want. So let's add the close button to the mobile menu as well.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### LINKED ISSUE #3172: Android mobile app top menu bug
**Describe the bug**

You can get stuck in the Android version of the mobile app, without any possibility to navigate in the app.

**To Reproduce**

Open Android mobile App in your Android smartphone or run it with Android Studio Emulator and:

1. Open top Menu an click on Security.
2. Scroll down to the bottom of the page.
3. Click on the top menu (three dots).
4. You can't click or navigate out of that screen.

### PR DESCRIPTION
**Pull request by faboweb**
Closes #3162 

**Description:**

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
this doesn't solve the issue and breaks our design patterns. there should always be a little x in the top right.

the issue that mario reported happens after you click one of the menu buttons like security or about, not the session screens.

**Comment by faboweb** [comment]
I attached the wrong issue number.

**Comment by jbibla** [comment]
ok. but still, why not the little `x`?

**Comment by faboweb** [comment]
because on Desktop it is this button. feel free to change it.

**Comment by jbibla** [comment]
ok i understand now. yeah, we should use the same top bar we use for the menu.

**Comment by jbibla** [comment]
Screen Shot 2019-11-29 at 10 48 18 AM

**Comment by jbibla** [comment]
simple fix should just be an `x` in the top right.

**Pull request closed without merging**
