### PR TITLE
Ana/fix available in Polkadot

### LINKED ISSUE #4748: Polkadot available balances not correct
You can try exploring with the address `163BLNST8JYqNTQ8RuK2sU2YLE6q9ChCShHAcmhWb7qgsLbq` in Lunie (production or develop), doesn't matter.

Lunie displays +13 DOTs available, but if you go to the modals and try to make any transaction, it will tell you there are no DOTs available (the problem is that in explore mode you cannot test this, so you will have to believe me xD). In fact, available in balanceV2 is a negative value in this case, which is impossible. 

Removing the `miscFrozen` from the calculation (which wasn't used in the old balance query) fixes this.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4748 

**Description:**

Fixes wrong available balance in Polkadot for query `balance` and renames the DOT png file (which I though I had done in #4699 but apparently forgot to commit)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f3c41c6fd2f6464317b2207--lunieio.netlify.app

**Comment by jbibla** [comment]
i don't understand what this is doing if it doesn't fix #4742 

also missing changelog

**Comment by Bitcoinera** [comment]
> i don't understand what this is doing if it doesn't fix #4742
> 
> also missing changelog and could use a lint

True, this one was left quite obscure. Fixing it

**Comment by Bitcoinera** [comment]
OK, let's wait for @faboweb here since he is the one who included the miscFrozen logic in balanceV2

**Comment by jbibla** [comment]
i hotfixed the image issue. there are now three 

```
dot.png
dot (old).png
new dot.png
```

so please revert the image rename here

**Comment by Bitcoinera** [comment]
> i hotfixed the image issue. there are now three:

How do we want to have three different image names if we already have the icon field in DB pointing to the right file? This is in production

**Pull request merged**
