### PR TITLE
[WIP] Fix polkadot e2e test

### LINKED ISSUE #4838: Failing Polkadot e2e test
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #4838 

**Description:**

Also upgrade chromedriver to v85.0.0

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f5a42afbf9d4d0b54e98922--lunieio.netlify.app

**Comment by mariopino** [comment]
Getting `Sending tokens failed: Broadcast was not successful: 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low).` in e2e test but it works in staging! :-/

**Comment by faboweb** [comment]
> Getting Sending tokens failed: Broadcast was not successful: 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low). in e2e test but it works in staging! :-/

using e2e tests against staging?

**Comment by Bitcoinera** [comment]
@mariopino are you still working on this?

**Comment by mariopino** [comment]
> still working on this @mariopino ?

Yap, I can take again!

**Comment by mariopino** [comment]
@faboweb please take the lead on this, I can't find the problem  :-/

**Comment by jbibla** [comment]
closing for now - @faboweb mario is passing this task off to you. if we are not going to solve this i think we should stop running the tests and remove it from the PR checks.

**Pull request closed without merging**
