### PR TITLE
Ana/quick fix for style glitch on session frame

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Fixes this:

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5effe5659dce2d6f5602bbaf--lunieio.netlify.app

**Comment by faboweb** [comment]
🚀 Deployed on https://5effe5658ed8b883e66a1f5d--lunieio.netlify.app

**Comment by faboweb** [comment]
How about adding icons to the account session modals? We could use the same icons as the list items in session-list

**Comment by Bitcoinera** [comment]
> How about adding icons to the account session modals? We could use the same icons as the list items in session-list

Good idea! I like it :woman_dancing:

**Comment by Bitcoinera** [comment]
Now this PR also fixes a very important style glitch: the TmSelectNetwork in the beginning of the Sign Up flow being cut and not displaying all of the networks:

**Pull request merged**
