### PR TITLE
Ana/fix signing for akash-mainnet not enabled

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Ah, seems you fixed it on production just now @faboweb ?

**Comment by faboweb** [comment]
🚀 Deployed on https://5f6e1e0e4810d8013fe90ea3--lunieio.netlify.app

**Comment by faboweb** [comment]
yes already fixed on master

**Comment by Bitcoinera** [comment]
> yes already fixed on master

But we still need this here or did you merge from master?

You can close this if you did

**Pull request merged**
