### PR TITLE
Fabo/4878 withdraw unstaked button

### LINKED ISSUE #4878: add withdraw unstaked tokens button in polkadot
What is this about? :eyes:

This is already done, right?

### PR DESCRIPTION
**Pull request by faboweb**
Closes #4878

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Missing some tests

**Comment by faboweb** [comment]
🚀 Deployed on https://5f5ff3438e6eac6a9e9f7c81--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
I think something went wrong? This PR only contains the changelogs currently. You forgot to push them maybe?

Difficult to test only changelogs :stuck_out_tongue_winking_eye:

**Comment by Bitcoinera** [comment]
unit tests are failing. I can help

**Comment by Bitcoinera** [comment]
Westend `5GNtHmp1XmHJkGnM7swchrNGDcJ3r9yaQkumDZYK8tuEeZjG` is good for testing

**Comment by Bitcoinera** [comment]
Nice

image

Do we really need a new component for this? We could just use a bunch of v-ifs inside the already existing UndelegateModal, don't you think? They are so similar

image

**Comment by Bitcoinera** [comment]
The Unstaking BalanceRow doesn't disappear immediately after doing the Withdraw Unstaked:

image

**Comment by faboweb** [comment]
> The Unstaking BalanceRow doesn't disappear immediately after doing the Withdraw Unstaked:

good question, need to investigate. maybe the tx doesn't do anything

**Comment by Bitcoinera** [comment]
In 4h the Westend account's funds will be claimable. Let's test this then

**Comment by Bitcoinera** [comment]
Oh no, I cannot test this anymore, what happened? Where did my claimable go??

image

**Comment by Bitcoinera** [comment]
Did you test it yourself @faboweb ?

**Comment by Bitcoinera** [comment]
Ah OK, I only had to merge develop

image

**Comment by Bitcoinera** [comment]
Works great! Only that strange CSS bug we've been suffering for some months now

Peek 2020-09-17 19-49

**Review by Bitcoinera — APPROVED** [review]

**Pull request merged**
