### PR TITLE
Ana/3199 mobile close button signin

### LINKED ISSUE #3199: Close/Go back button for "Sign In" also in mobile/reduced screen
**Is your feature request related to a problem? Please describe.**

When I try to sign in in mobile but then I fail or I change my mind for some reason, I would like as an user to have a button to go back to Lunie without having to sign in. 

Right now the only option available is to click on the Lunie logo, which is not great UX, because I needed a while to figure it out, for example.

**Describe the solution you'd like**

Put an x symbol just like the one you get when you open the navbar.

**Describe alternatives you've considered**

**Additional context**

Here a screenshot of how it now looks like the Sign In screen:

image

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3199 

**Description:**

Added a close button for the whole sign in process that shows up in screens thinner than 1023px.

Here a screenshot:

image

Now looking at it again I am thinking it would look better with the user-box class as the background :thinking: 
Yes, I think I will also add that (and probably a couple of tests are missing too, oops)

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
While I was writing the description I decided to change this PR to draft as I still want to do a couple of changes :sweat_smile:

**Comment by Bitcoinera** [comment]
Well, there are some details I definitely need to take care of xD

image

**Comment by faboweb** [comment]
> While I was writing the description I decided to change this PR to draft as I still want to do a couple of changes 😅

How do you do that??!?!

**Comment by faboweb** [comment]
Nice

**Pull request merged**
