### PR TITLE
Fabo/polkadot address creation

### LINKED ISSUE #3621: Polkadot Account Management
Polkadot accounts look a little different then Cosmos ones
- we will not need a pubkey for signing or displaying
- we can't extract the privatekey somehow (will just store seed and restore key when signing)

Need to fix prefix logic in sign in processes (done)

On account creation we need to make the controller account the same as the stash account for simplicity: https://wiki.polkadot.network/docs/en/learn-staking#accounts

### PR DESCRIPTION
**Pull request by faboweb**
Does Polkador address creation. Requires #3625  and https://github.com/luniehq/lunie-api/pull/376 and https://github.com/luniehq/lunie-api/pull/386

Closes #3621

### CODE REVIEW

**Comment by jbibla** [comment]
can you link to the PRs you're referencing?

**Comment by faboweb** [comment]
Needs manual testing

**Comment by faboweb** [comment]
Ready

**Comment by jbibla** [comment]
trying to manually test - but the networks page isn't loading and kusama is not on the select network screen

**Comment by faboweb** [comment]
Do  test with https://deploy-preview-3632--lunieio.netlify.com/networks?api=https%3A%2F%2Fstaging-api.lunie.io

**Comment by faboweb** [comment]
e2e tests will pass when api is released

**Comment by Bitcoinera** [comment]
> Do test with https://deploy-preview-3632--lunieio.netlify.com/networks?api=https%3A%2F%2Fstaging-api.lunie.io

The issue is that now Kusama is commented out there right?

**Comment by Bitcoinera** [comment]
It is working! 🎉  I just tried in local (both FE and API) and great.

Only one question. I thought we decided to have the `polka` prefix at the beginning of each Polkadot/Kusama address?

What happened with this idea?

The one I got is: 5EVYeZZo1tzG7mRizkFBPQkwrnL7VB7juNzDzWxZsm4ESM19

**Comment by Bitcoinera** [comment]
> in all the other tools they will not see a polka1234 address

Yeah, true. It would be too confusing

**Pull request merged**
