### PR TITLE
colw/yarn-2-npm

### PR DESCRIPTION
**Pull request by colw**
**Description:**

Convert all instances of yarn to npm.

If you prefer you may use yarn locally (unsupported), but please do not commit yarn.lock.

Note that all CI is run using npm.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
nice! 

> please do not commit yarn.lock

you could add it to the .gitignore

**Comment by faboweb** [comment]
Netlify:
```
7:06:46 PM: Waiting for other deploys from your team to complete
7:07:06 PM: Build ready to start
7:07:12 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
7:07:12 PM: build-image tag: v3.3.2
7:07:12 PM: buildbot version: a2bab682ae0761baa4d123ebd00c57be933655dc
7:07:12 PM: Fetching cached dependencies
7:07:12 PM: Starting to download cache of 249.5MB
7:07:14 PM: Finished downloading cache in 1.739866086s
7:07:14 PM: Starting to extract cache
7:07:25 PM: Finished extracting cache in 11.010161141s
7:07:25 PM: Finished fetching cache in 12.901975432s
7:07:25 PM: Starting to prepare the repo for build
7:07:25 PM: Preparing Git Reference pull/3138/head
7:07:27 PM: Starting build script
7:07:27 PM: Installing dependencies
7:07:27 PM: Started restoring cached node version
7:07:30 PM: Finished restoring cached node version
7:07:30 PM: Attempting node version '10.15.0' from .nvmrc
7:07:31 PM: v10.15.0 is already installed.
7:07:32 PM: Now using node v10.15.0 (npm v6.4.1)
7:07:32 PM: Attempting ruby version 2.6.2, read from environment
7:07:34 PM: Using ruby version 2.6.2
7:07:34 PM: Using PHP version 5.6
7:07:34 PM: Started restoring cached node modules
7:07:34 PM: Finished restoring cached node modules
7:07:34 PM: Installing NPM modules using NPM version 6.4.1
7:08:24 PM: > husky@3.0.8 preuninstall /opt/build/repo/node_modules/husky
7:08:24 PM: > node husky uninstall
7:08:25 PM: husky > Uninstalling git hooks
7:08:25 PM: husky > Done
7:08:25 PM: > yorkie@2.0.0 uninstall /opt/build/repo/node_modules/yorkie
7:08:25 PM: > node bin/uninstall.js
7:08:25 PM: husky
7:08:25 PM: uninstalling Git hooks
7:08:25 PM: done
7:08:25 PM: npm
7:08:25 PM: WARN rm
7:08:25 PM:  not removing /opt/build/repo/node_modules/.bin/jest as it wasn't installed by /opt/build/repo/node_modules/jest
7:08:25 PM: npm
7:08:25 PM: WARN rm not removing /opt/build/repo/node_modules/.bin/rimraf as it wasn't installed by /opt/build/repo/node_modules/rimraf
7:08:25 PM: npm WARN
7:08:25 PM: rm not removing /opt/build/repo/node_modules/.bin/which as it wasn't installed by /opt/build/repo/node_modules/which
7:08:25 PM: npm WARN rm not removing /opt/build/repo/node_modules/.bin/uglifyjs as it wasn't installed by /opt/build/repo/node_modules/uglify-js
7:08:25 PM: npm WARN rm not removing /opt/build/repo/node_modules/.bin/semver as it wasn't installed by /opt/build/repo/node_modules/semver
7:08:25 PM: npm WARN
7:08:25 PM:  rm not removing /opt/build/repo/node_modules/.bin/regjsparser as it wasn't installed by /opt/build/repo/node_modules/regjsparser
7:08:25 PM: npm WARN rm not removing /opt/build/repo/node_modules/.bin/json5 as it wasn't installed by /opt/build/repo/node_modules/json5
7:08:25 PM: npm
7:08:25 PM: WARN rm not removing /opt/build/repo/node_modules/.bin/jsesc as it wasn't installed by /opt/build/repo/node_modules/jsesc
7:08:25 PM: npm WARN
7:08:25 PM: rm not removing /opt/build/repo/node_modules/.bin/is-ci as it wasn't installed by /opt/build/repo/node_modules/is-ci
7:08:25 PM: npm WARN
7:08:25 PM:  rm not removing /opt/build/repo/node_modules/.bin/cssesc as it wasn't installed by /opt/build/repo/node_modules/cssesc
7:08:46 PM: > secp256k1@3.7.1 install /opt/build/repo/node_modules/secp256k1
7:08:46 PM: > npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."
7:08:46 PM: > secp256k1@3.7.1 rebuild /opt/build/repo/node_modules/secp256k1
7:08:46 PM: > node-gyp rebuild
7:08:48 PM: make: Entering directory '/opt/build/repo/node_modules/secp256k1/build'
7:08:48 PM:   CXX(target) Release/obj.target/secp256k1/src/addon.o
7:08:49 PM:   CXX(target) Release/obj.target/secp256k1/src/privatekey.o
7:08:50 PM: ../src/privatekey.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE privateKeyNegate(Nan::NAN_METHOD_ARGS_TYPE)’:
7:08:50 PM: ../src/privatekey.cc:73:61: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
7:08:50 PM:    secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
7:08:50 PM:                                                              ^
7:08:50 PM: At global scope:
7:08:50 PM: cc1plus: warning: unrecognized command line option ‘-Wno-nonnull-compare’
7:08:50 PM:   CXX(target) Release/obj.target/secp256k1/src/publickey.o
7:08:52 PM:   CXX(target) Release/obj.target/secp256k1/src/signature.o
7:08:53 PM:   CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
7:08:54 PM:   CXX(target) Release/obj.target/secp256k1/src/ecdh.o
7:08:55 PM:   CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
7:08:57 PM:   CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
7:08:57 PM:   CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
7:08:57 PM:   SOLINK_MODULE(target) Release/obj.target/secp256k1.node
7:08:57 PM:   COPY Release/secp256k1.node
7:08:57 PM: make: Leaving directory '/opt/build/repo/node_modules/secp256k1/build'
7:08:57 PM: > tiny-secp256k1@1.1.3 install /opt/build/repo/node_modules/tiny-secp256k1
7:08:57 PM: > npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."
7:08:58 PM: > tiny-secp256k1@1.1.3 build /opt/build/repo/node_modules/tiny-secp256k1
7:08:58 PM: > node-gyp rebuild
7:08:58 PM: make: Entering directory '/opt/build/repo/node_modules/tiny-secp256k1/build'
7:08:58 PM:   CXX(target) Release/obj.target/secp256k1/native/addon.o
7:08:59 PM: ../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&, const A&) [with long unsigned int index = 2ul; I = Nan::FunctionCallbackInfo<v8::Value>; A = v8::Local<v8::Object>]’:
7:08:59 PM: ../native/addon.cpp:142:50:   required from here
7:08:59 PM: ../native/addon.cpp:80:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
7:08:59 PM:    if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
7:08:59 PM:                      ^
7:08:59 PM: ../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&, const A&) [with long unsigned int index = 1ul; I = Nan::FunctionCallbackInfo<v8::Value>; A = v8::Local<v8::Object>]’:
7:08:59 PM: ../native/addon.cpp:174:49:   required from here
7:08:59 PM: ../native/addon.cpp:80:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
7:08:59 PM: ../native/addon.cpp: In instantiation of ‘unsigned int {anonymous}::assumeCompression(const I&) [with long unsigned int index = 1ul; I = Nan::FunctionCallbackInfo<v8::Value>]’:
7:08:59 PM: ../native/addon.cpp:189:46:   required from here
7:08:59 PM: ../native/addon.cpp:87:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
7:08:59 PM:    if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
7:08:59 PM:                      ^
7:08:59 PM: ../native/addon.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE eccPrivateSub(Nan::NAN_METHOD_ARGS_TYPE)’:
7:08:59 PM: ../native/addon.cpp:240:53: warning: ignoring return value of ‘int secp256k1_ec_privkey_negate(const secp256k1_context*, unsigned char*)’, declared with attribute warn_unused_result [-Wunused-result]
7:08:59 PM:   secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
7:08:59 PM:                                                      ^
7:09:00 PM:   CC(target) Release/obj.target/secp256k1/native/secp256k1/src/secp256k1.o
7:09:01 PM:   SOLINK_MODULE(target) Release/obj.target/secp256k1.node
7:09:02 PM:   COPY Release/secp256k1.node
7:09:02 PM: make: Leaving directory '/opt/build/repo/node_modules/tiny-secp256k1/build'
7:09:02 PM: > yorkie@2.0.0 install /opt/build/repo/node_modules/yorkie
7:09:02 PM: > node bin/install.js
7:09:02 PM: CI detected, skipping Git hooks installation
7:09:02 PM: > chromedriver@78.0.1 install /opt/build/repo/node_modules/chromedriver
7:09:02 PM: > node install.js
7:09:02 PM: Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
7:09:02 PM: Downloading from file:  https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
7:09:02 PM: Saving to file: /opt/buildhome/tmp/78.0.3904.70/chromedriver/chromedriver_linux64.zip
7:09:02 PM: Received 781K...
7:09:02 PM: Received 1568K...
7:09:02 PM: Received 2352K...
7:09:02 PM: Received 3136K...
7:09:02 PM: Received 3920K...
7:09:02 PM: Received 4704K...
7:09:02 PM: Received 5398K total.
7:09:02 PM: Extracting zip contents
7:09:03 PM: Copying to target path /opt/build/repo/node_modules/chromedriver/lib/chromedriver
7:09:03 PM: Fixing file permissions
7:09:03 PM: Done. ChromeDriver binary available at /opt/build/repo/node_modules/chromedriver/lib/chromedriver/chromedriver
7:09:03 PM: > husky@3.0.8 install /opt/build/repo/node_modules/husky
7:09:03 PM: > node husky install
7:09:03 PM: husky > Setting up git hooks
7:09:03 PM: CI detected, skipping Git hooks installation.
7:09:03 PM: husky > Done
7:09:03 PM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/core-js
7:09:03 PM: > node postinstall || echo "ignore"
7:09:03 PM: > ejs@2.7.2 postinstall /opt/build/repo/node_modules/ejs
7:09:03 PM: > node -e "console.log('Thank you for installing \u001b[35mEJS\u001b[0m: built with the \u001b[32mJake\u001b[0m JavaScript build tool (\u001b[32mhttps://jakejs.com/\u001b[0m)\n');"
7:09:03 PM: Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
7:09:04 PM: > husky@3.0.8 postinstall /opt/build/repo/node_modules/husky
7:09:04 PM: > opencollective-postinstall || exit 0
7:09:04 PM: (node:1159) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
7:09:07 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
7:09:07 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:09:07 PM: added 357 packages from 183 contributors, removed 173 packages, updated 1719 packages and audited 61686 packages in 91.6s
7:09:07 PM: found 65 low severity vulnerabilities
7:09:07 PM:   run `npm audit fix` to fix them, or `npm audit` for details
7:09:07 PM: NPM modules installed
7:09:07 PM: Started restoring cached go cache
7:09:07 PM: Finished restoring cached go cache
7:09:07 PM: unset GOOS;
7:09:07 PM: unset GOARCH;
7:09:07 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
7:09:07 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
7:09:07 PM: go version >&2;
7:09:07 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
7:09:07 PM: go version go1.12 linux/amd64
7:09:07 PM: Installing missing commands
7:09:07 PM: Verify run directory
7:09:07 PM: Executing user command: yarn && yarn build
7:09:07 PM: /usr/local/bin/build: line 60: yarn: command not found
7:09:07 PM: Skipping functions preparation step: no functions directory set
7:09:07 PM: Caching artifacts
7:09:07 PM: Started saving node modules
7:09:07 PM: Finished saving node modules
7:09:07 PM: Started saving pip cache
7:09:07 PM: Finished saving pip cache
7:09:07 PM: failed during stage 'building site': Build script returned non-zero exit code: 127
7:09:07 PM: Started saving emacs cask dependencies
7:09:07 PM: Finished saving emacs cask dependencies
7:09:07 PM: Started saving maven dependencies
7:09:07 PM: Finished saving maven dependencies
7:09:07 PM: Started saving boot dependencies
7:09:07 PM: Finished saving boot dependencies
7:09:07 PM: Shutting down logging, 5 messages pending
```

**Comment by colw** [comment]
Resolutions are yarn only ☝️

**Comment by faboweb** [comment]
switched netlify to use npm

**Comment by faboweb** [comment]
We are sticking with Yarn.

**Pull request closed without merging**
