### PR TITLE
[WIP] Use Polkadot API HttpProvider in frontend and extension

### LINKED ISSUE #4888: Use Polkadot httpProvider in frontend
**Is your feature request related to a problem? Please describe.**

We are not using polkadot rpc subscriptions in frontend so we don't really need a websocket provider.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #4888 

**Description:**

**Notes:**

- **WARNING! Only works on Westend!** This include a weird hack in order to avoid update DB.
- Node providers needs to provide a new endpoint for Http RPC (http rpc port is 9933, ws rpc port is 9944) and also enable CORS for all our origins or set a permissive rule '*'
- As expected does not support subscriptions nor 'on' event emitters:

```
2020-09-15 09:24:56        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2020-09-15 09:24:56        API-HTTP: HTTP Provider does not have 'on' emitters, use WebSockets instead
```

**Related parity polkadot args:**

```
--rpc-external
    `--unsafe-rpc-external` to suppress the warning if you understand the risks.
--unsafe-rpc-external
    Same as `--rpc-external`.
--rpc-cors <ORIGINS>
--rpc-methods <METHOD SET>
    - `Auto`: Acts as `Safe` if RPC is served externally, e.g. when `--{rpc,ws}-external` is passed,
--rpc-port <PORT>
```

`--unsafe-rpc-external ` was used.

**nginx conf:**

```
        location /httprpc {
               proxy_hide_header 'Access-Control-Allow-Origin';
               add_header 'Access-Control-Allow-Origin' '*';
               proxy_pass http://localhost:9933;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
```

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
On Polkadot in the app I get this:

image

**Comment by mariopino** [comment]
> On Polkadot in the app I get this:
> 
> image
> 
> In the API I get this:
> 
> ```
> (node:13065) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 polkadot_NEW_BLOCK listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
> ```
> 
> 🙀
> 
> OK, but it is a WIP 😅 sorry if it is too much pressure

Jaja no, no prob! Only issue is that you need to test using Westend, as right now it's the only http rpc endpoint available.

**Comment by Bitcoinera** [comment]
> Jaja no, no prob! Only issue is that you need to test using Westend, as right now it's the only http rpc endpoint available.

With Westend I also get this error :shrug: 

image

**Comment by mariopino** [comment]
> > Jaja no, no prob! Only issue is that you need to test using Westend, as right now it's the only http rpc endpoint available.
> 
> With Westend I also get this error 🤷
> 
> image
> 
> And this one 👀 memory leak
> 
> ```
> (node:15362) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 polkadot-testnet_NEW_BLOCK listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
> ```

Hey Ana, the first error is expected, please check PR description ;-)

The second is not related to this PR as http provider is not used in API yet.

**Comment by faboweb** [comment]
Great PR. Note: the code should just replace polkadot-node-subscription.js

**Comment by Bitcoinera** [comment]
> The second is not related to this PR as http provider is not used in API yet.

Yeah, I have seen this message before, but it seems to come up more often in this PR. Wonder why :thinking:

**Comment by mariopino** [comment]
mmm tried using HttpProvider in API, polkadot api inicialization is fast!!!! but got this beautiful huge mem leak & stack trace after a minute:

```
<--- Last few GCs --->

[5344:000002086AA2D940]   159973 ms: Mark-sweep 2042.5 (2053.2) -> 2041.6 (2053.4) MB, 3663.3 / 0.1 ms  (average mu = 0.062, current mu = 0.003) allocation failure scavenge might not succeed
[5344:000002086AA2D940]   162930 ms: Mark-sweep 2043.0 (2053.4) -> 2042.3 (2053.7) MB, 2952.2 / 0.1 ms  (average mu = 0.034, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0262a82008d1 <JSObject>
    0: builtin exit frame: concat(this=0x032433e90d49 <JSArray[0]>,0x032433e90d69 <JSArray[1]>,0x032433e90d49 <JSArray[0]>)

    1: newBlockHandler [0000016CA53A72D9] [C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\api\lib\block-listeners\polkadot-node-subscription.js:~131] [pc=0000022BEF78357D](this=0x01df1b32c471 <PolkadotNodeSubscription map = 000000BAF907CC09>,1621781)
    2: checkF...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7E7B8363F napi_wrap+128063
 2: 00007FF7E7B22836 v8::base::CPU::has_sse+35142
 3: 00007FF7E7B234F6 v8::base::CPU::has_sse+38406
 4: 00007FF7E8339F4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7E8322021 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7E81EE57C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7E81F97D0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7E81F62F4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7E81EBB13 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7E81EA184 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7E82048F0 v8::internal::Factory::AllocateRawWithAllocationSite+96
12: 00007FF7E820D2BB v8::internal::Factory::NewJSArrayWithUnverifiedElements+171
13: 00007FF7E820C9B0 v8::internal::Factory::NewJSArray+192
14: 00007FF7E80D7235 v8::internal::FeedbackNexus::ic_state+58149
15: 00007FF7E82E9B5E v8::internal::Builtins::builtin_handle+306942
16: 00007FF7E82E77C2 v8::internal::Builtins::builtin_handle+297826
17: 00007FF7E82E73FE v8::internal::Builtins::builtin_handle+296862
18: 00007FF7E8784EDD v8::internal::SetupIsolateDelegate::SetupHeap+546893
19: 0000022BEF78357D 
[nodemon] app crashed - waiting for file changes before starting...
```

**PD**: Now this works in polkadot, kusama and westend

**Comment by mariopino** [comment]
Notes:

- Memory leak is caused by the loop in `checkForNewBlock`, first time this.height = 0, so in the case of Kusama, it tries to handle 4 millions of block. 
- Should be another subscription in another place as I'm getting this error:

```
2020-09-16 18:51:28             DRR: Error: HTTP Provider does not have subscriptions, use WebSockets instead
    at HttpProvider.subscribe (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-provider\http\index.js:160:11)
    at C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\index.js:289:21
    at new Promise (<anonymous>)
    at Rpc._createSubscriber (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\index.js:288:12)
    at Observable._subscribe (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\index.js:333:38)
    at Observable._trySubscribe (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\node_modules\rxjs\internal\Observable.js:30:22)
    at CatchOperator.call (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\node_modules\rxjs\internal\operators\catchError.js:30:23)
    at Observable.subscribe (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\node_modules\rxjs\internal\Observable.js:25:31)
    at DistinctUntilChangedOperator.call (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\node_modules\@polkadot\rpc-core\node_modules\rxjs\internal\operators\distinctUntilChanged.js:27:23)
```

**Comment by mariopino** [comment]
Asked Jaco about and he confirms that 99% of `api.derive.*` queries use subscriptions, so sadly it seems that doesn't make sense to use HttpProvider in API.

**Comment by faboweb** [comment]
going with sidecar for now

**Pull request closed without merging**
