### PR TITLE
Ana/hotfix show on ledger in user menu

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Simple hotfix: the TmFormMsg wasn't properly registered

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
weird that commit there "merge from master in release"? :eyes:

**Comment by faboweb** [comment]
test fails and can you show a screenshot that is works?

**Comment by Bitcoinera** [comment]
> test fails and can you show a screenshot that is works?

You can see that `TmFormMsg` wasn't registered before

**Comment by Bitcoinera** [comment]
Weird with the tests

**Comment by Bitcoinera** [comment]
31 files changed?

**Comment by Bitcoinera** [comment]
Something is going on with the intercom button in tests it seems:

```
    +         <a
    +           class="intercom-button"
    +         >
```

**Comment by jbibla** [comment]
> Something is going on with the intercom button in tests it seems:

probably related to the hotfix i pushed

**Comment by Bitcoinera** [comment]
> probably related to the hotfix i pushed - just update the snapshots i think

This is the first thing I actually tried :sweat_smile:

**Comment by Bitcoinera** [comment]
Mmm, there are files in master that are slightly different than in develop :thinking: 

I think we need a PR just to make develop be the same than master

**Comment by Bitcoinera** [comment]
nooo, I need to reopen this PR or something. I shouldn't have merged develop, only master

**Comment by faboweb** [comment]
🚀 Deployed on https://5f3bacc20f4976905039f550--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
????

**Comment by Bitcoinera** [comment]
:smoking:

**Pull request closed without merging**
