### PR TITLE
Jordan/themes

### PR DESCRIPTION
**Pull request by jbibla**
**Description:**
🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨THEMES 🎨 🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨🎨

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
I think I prefer the old blue...

image

**Comment by Bitcoinera** [comment]
This looks very... galactic. Green and purple... Risky

image

**Comment by Bitcoinera** [comment]
Sorry, I prefer the old colors xD

**Comment by jbibla** [comment]
the colors for cosmos / gaia are from the official cosmos style guide: https://cosmos.network/design

try switching networks 🙃

**Comment by mariopino** [comment]
Some comments:

- I **love** the kusama theme (and the theming thing in general!)
- For Cosmos amounts discussion, I think I like more the idea behind (to have 3 "weights" for amounts) that the color itself ^^
- I don't like too much the idea of having different colors for networks. IMO it can add some confusion.

**Comment by jbibla** [comment]
> I don't like too much the idea of having different colors for networks. IMO it can add some confusion.

thanks for the feedback. maybe it can be opt-in with a "use network theme colors" checkbox.

**Comment by mariopino** [comment]
> > I don't like too much the idea of having different colors for networks. IMO it can add some confusion.
> 
> thanks for the feedback. maybe it should be opt-in with a "use network theme colors" checkbox.
> 
> i can make a simple "Lunie light theme" and "Lunie dark theme" for users that isn't based on network color schemes.
> 
> everyone is used to the lunie colors but it's actually just old cosmos colours - this is why our website is so different. multi network world requires a makeover!

Sorry for the confusion, what I want to say in my last point is related to amounts (not networks! was a mistake editing the comment).

I really like the use of different themes for each network!

**Comment by jbibla** [comment]
> Sorry for the confusion, what I want to say in my last point is related to amounts (not networks! was a mistake editing the comment). I was thinking about the color for the main staking denom should look consistent across themes

lol ok!  yeah that's a good point. i can make the critical amounts the same colors across themes.

**Comment by Bitcoinera** [comment]
xD

**Pull request merged**
