### PR TITLE
Ana/replace x3ngm for ungm

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Small but important fix. Upgrading to the new e-Money blockchain

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
this fix doesn't work independently from the API change. in the future please consider creating changes that are non breaking

**Comment by Bitcoinera** [comment]
> this fix doesn't work independently from the API change. in the future please consider creating changes that are non breaking

The API PR was just merged today xD

**Comment by faboweb** [comment]
to staging. but we can't independently release FE and API now

**Comment by Bitcoinera** [comment]
> to staging. but we can't independently release FE and API now

Oh, I understand now. Well, we technically can. Just need to get this one commit out right?

**Pull request merged**
