### PR TITLE
Ana/4326 add unit test for new components

### LINKED ISSUE #4326: Epic: add unit tests for all the new components
Once we finish with user accounts and have the paywall in place for Premium we should take the time to create the unit tests for all the new components.

These are:

- all the ones in the account folder

- the account module in store

- the new `recoverFromPrivatekey` function in the keystore module in store

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4326

**Description:**

Opening it as WIP first to see the codecov result, case it is still properly working. Let's check

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5efa2c30db0b2101c2f65e11--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Where is codecov? :eyes:

**Comment by Bitcoinera** [comment]
:facepalm:

**Comment by Bitcoinera** [comment]
Mmm, I like this number:



It's a sign! :bell:

**Comment by Bitcoinera** [comment]
@faboweb can you help me a little with the `revealSeedPhrase` function one? It is the only one I am missing. How can I make it to have the wallet stored and then test it. I get all the time `undefined`, but in extension I'd get the secret.

Or do I need to mock everything up?

Thanks :pray:

**Comment by Bitcoinera** [comment]
Good to go!

**Pull request merged**
