### PR TITLE
Ana/fix objectObject in polkadot referendum

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Before:

image

After:

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
OK, as requested, with name and surname:

image

**Comment by jbibla** [comment]
is there a way to display all the data instead of just one value?

Screen Shot 2020-10-06 at 2 23 14 PM

**Comment by Bitcoinera** [comment]
> is there a way to display _all the data_ instead of just one value?

Yes, sure. Quite easy

**Comment by Bitcoinera** [comment]
Final state (can still be improved):

image

**Review by jbibla — APPROVED** [review]

**Pull request merged**
