### PR TITLE
WIP Aleksei/example of error handling

### PR DESCRIPTION
**Pull request by faboweb**
Closes #ISSUE

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
This is not helping with Sentry errors in the update functions, right?

**Comment by faboweb** [comment]
Ah your solution is to now add in every update function 

```
if (data.error) { this.error = data.error; return }
```

?

**Comment by Bitcoinera** [comment]
I find @iambeone 's solution super elegant and desirable. But yes, @faboweb is right that this doesn't help with the Sentry errors... sadly the `update` function is still being fired.

**Comment by iambeone** [comment]
No, the update function is not fired unless we will decide to fire them in code.

**Comment by iambeone** [comment]
With the wrong api url set. Without this link
image
With 
image
With this link we can manage errors as we want. For example getting just first error
image
Or pass any data to end-function and trigger it. Or just console.log the error, or do something other.

**Comment by Bitcoinera** [comment]
> With the wrong api url set. Without this link
> image
> With
> image
> With this link we can manage errors as we want. For example getting just first error
> image
> Or pass any data to end-function and trigger it. Or just console.log the error, or do something other.

Wow! Amazing Aleksei!!! What an incredible finding!

I will try it out in a bit :wink:

**Comment by faboweb** [comment]
Ok I get it. Nice solution. The error function of Apollo in the components is still triggered with this?

**Comment by iambeone** [comment]
>>The error function of Apollo in the components is still triggered with this?
Need to check it

**Comment by faboweb** [comment]
This is superseeded by #3531 ?

**Pull request closed without merging**
