### PR TITLE
Ana/3925 use proper keyboar input for mobile android 6

### LINKED ISSUE #3925: Add proper keyboard input for mobile for Android 6 where there is no dot for decimals
Kusama final battle!

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3925 (at least aims to)

**Description:**

I don't have Android Studio to test this, but it is not harmful at all (one line change 😝 ) and we can so give it a shot 🤷 Better than nothing

I was reading quite a couple of threads about this, but mostly are React Native developers complaining. And our Android code comes directly from capacitor, so it is a very concrete case.

Let's just give it a shot

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
I also learned reading on Google that this is not an specific error of Android 6, but of a device... For example, Samsung devices seem to be largely affected

**Comment by jbibla** [comment]
does it effect the web version?

**Comment by faboweb** [comment]
Would be great to test this before merging

**Comment by Bitcoinera** [comment]
> Would be great to test this before merging

Why is there no online Android Studio 😅

**Comment by Bitcoinera** [comment]
@mariopino could you please check this 🙏

**Comment by faboweb** [comment]
tough to test but doesn't effect web

**Pull request merged**
