### PR TITLE
Ana/4512 fix dashboard

### LINKED ISSUE #4512: Fix Dashboard (add metric from currently used queries)
Deprecate overview and use rewards and balance instead

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4512 

**Description:**

Looking good. Seems to be working. Still need to check with Substrate accounts

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
The main thing is working :tada: But guess to fix the numbers in production there still some work to do. There must be pretty wrong values there

**Comment by faboweb** [comment]
Looking great

**Comment by Bitcoinera** [comment]
Weird that the test check fails, locally it passes them all :eyes:

**Comment by faboweb** [comment]
pushed all your snaps?

**Pull request merged**
