### PR TITLE
Fabo/fix undelegating stake not in total

### PR DESCRIPTION
**Pull request by faboweb**
Undelegations were not counted towards the total balance

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Nice! I saw this, but I fixed this in #4668 

image

image

Or should we fix it here too (I simple used uniqWith to erase the duplicates)

**Comment by jbibla** [comment]
why are there duplicates?

**Comment by Bitcoinera** [comment]
> why are there duplicates?

Good question

**Comment by Bitcoinera** [comment]
This was great the way it was. The duplicates will just need another PR

**Pull request merged**
