### PR TITLE
Ana/fix akash mainnet logo on user menu

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Before:

image

After:

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Maybe we could remove `address.icon` and just use always `currentNetwork.icon`. I mean, what is the use case for `address.icon`? At least, currently

**Comment by faboweb** [comment]
🚀 Deployed on https://5f6e1d0a131efd0112b54cd8--lunieio.netlify.app

**Review by faboweb — APPROVED** [review]

**Review by faboweb — CHANGES_REQUESTED** [review]
why `currentNetwork`?

**Comment by faboweb** [comment]
FOr now I pushed the akash-mainnet logo to master

**Comment by Bitcoinera** [comment]
> why `currentNetwork`?

Because it is the network Object which contains the icon field

**Comment by faboweb** [comment]
But currentNetwork is not the network of the individual account it is the currently visible network. You need to look for the network based on the networkId in the account.

**Comment by Bitcoinera** [comment]
> But currentNetwork is not the network of the individual account it is the currently visible network. You need to look for the network based on the networkId in the account.

Ah true xD! Thanks for the remark. Always getting confused there :pray:

**Comment by Bitcoinera** [comment]
OK, now it is good! Fixing the address.icon in UserMenu :+1: (same like we did with `networkId`)

**Review by faboweb — APPROVED** [review]

**Pull request merged**
