### PR TITLE
handle infinity numbers

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Just added the case for numbers bigger to 99 trillion in the `bigFigure` filter, so it returns infinity (∞)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🙈  does this actually happen or is it just a conversion error?

**Comment by Bitcoinera** [comment]
> 🙈 does this actually happen or is it just a conversion error?

It was a conversion error but I thought it was a good idea to implement this too

**Comment by Bitcoinera** [comment]
Agh, e2e still gets stuck in the first run...

**Comment by faboweb** [comment]
I don't think this will ever happen and only appeared by a sever bug. Let's not add not needed code.

**Comment by Bitcoinera** [comment]
> I don't think this will ever happen and only appeared by a sever bug. Let's not add not needed code.

We never thought we would deal with billions and here we are. Especially in testnets anything is possible 🤷‍♀  But OK (plus the infinity symbol is mega cool)

**Pull request closed without merging**
