### PR TITLE
Ana/3699 refactor to delete components/wallet and add session folder

### LINKED ISSUE #3699: Refactor folders in the FE to delete the `src/components/wallet` folder
This `wallet` folder in components is too confusing.

`PageTransactions` should go into the `transactions` folder and `PagePortfolio` into `common`.

Unit tests should also apply these changes

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3699 

**Description:**

The big and ultimate folder refactor. I have been wanting to do this for so long :star_struck: 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f7dc23115989b0e754d8244--lunieio.netlify.app

**Comment by jbibla** [comment]
i don't agree with moving more stuff into `/common` 

can you make this only about moving session stuff into a session folder? then we can merge without argument.

**Comment by Bitcoinera** [comment]
> i don't agree with moving more stuff into `/common`

I only added PagePortfolio :sweat_smile:  Where should I put this one instead?

**Comment by jbibla** [comment]
i don't know but this PR can be simple and straightforard and only about sessions

**Comment by Bitcoinera** [comment]
> i don't know but this PR can be simple and straightforard and only about sessions

OK, the wallet thing I can do it in another PR... :sob: although I have waited for so long to get rid of the infamous `wallet` folder

**Comment by Bitcoinera** [comment]
SessionFrame belongs to `common`, IMO, You agree, right?

**Comment by Bitcoinera** [comment]
image

:point_up: This is what I did that wasn't `session` related. I think it is fine. I'm testing everything and it's all good

**Comment by Bitcoinera** [comment]
OK, so what to do. Should I split the deleting wallet folder and do it in another PR or is it fine?

**Comment by jbibla** [comment]
did you check that the extension is working as expected? missing changelog...

**Comment by Bitcoinera** [comment]
> did you check that the extension is working as expected? missing changelog...

Yes, I did, of course :wink:  Everything is good. Adding changelog

**Review by jbibla — APPROVED** [review]

**Pull request merged**
