### PR TITLE
[WIP] Fix Kusama proposal not loading properly

### LINKED ISSUE #4969: Getting eternal loader while opening a Kusama governance proposal
**Describe the bug**

Proposal:

https://staging--lunieio.netlify.app/kusama/proposals/referendum-85

**To Reproduce**

Open `/kusama/proposals/referendum-85` in latest develop.
Got console error: "TypeError: _vm.proposal.detailedVotes.timeline is null"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #4969 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
are you sure the proposal was not loading because of this?

**Comment by faboweb** [comment]
🚀 Deployed on https://5f69e5384516301974fcd271--lunieio.netlify.app

**Comment by jbibla** [comment]
remove the console logs

**Comment by mariopino** [comment]
> are you sure the proposal was not loading because of this?

image

**Comment by Bitcoinera** [comment]
How can we reproduce? Is this only happening on staging netlify?

**Comment by mariopino** [comment]
> How can we reproduce? Is this only happening on staging netlify?

also in local

**Comment by faboweb** [comment]
still an issue?

**Pull request closed without merging**
