### PR TITLE
Ana/add kava stuff

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Adds the basic stuff that Kava needs to live also in our FE.

The only thing I'd change is the PNG file I used for the KAVA currency. I had to use GIMP and it is a bit pixeled. We should ask instead the Kava team.

Some screenshots. Super easy integration (except for the high fees):

image

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
lol maybe ask Charlie to help

**Comment by Bitcoinera** [comment]
> lol maybe ask Charlie to help

It is not Charlie, we just need to ask Kava team for their icons xD

**Comment by jbibla** [comment]
twitter profiles are a good place for images

https://pbs.twimg.com/profile_images/1240692119150329856/ECfmsFee_400x400.png

**Comment by Bitcoinera** [comment]
> twitter profiles are a good place for images
> 
> https://pbs.twimg.com/profile_images/1240692119150329856/ECfmsFee_400x400.png

Thanks! But I already got that one. Actually from the same place than you 😉 

I was searching for the red one for the currency but that one is a bit harder to find

**Comment by faboweb** [comment]
Merging can improve later

**Pull request merged**
