### PR TITLE
Ana/deactivate loader in development environment

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

It is becoming annoying to get this loader every time you make any change in the code

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
you can't do anything anyway while the loader is there / isn't there until the app is loader.

**Comment by Bitcoinera** [comment]
> you can't do anything anyway while the loader is there / isn't there until the app is loader.

I think it does delay in fact a bit. But also, it is super annoying

**Comment by Bitcoinera** [comment]
What does everyone else think? I find it also distracting. Why do we need to see the loader at all while developing?

**Comment by jbibla** [comment]
if it is adding a perceived delay we should consider changing it?

**Comment by faboweb** [comment]
No, it is reducing the perceived delay imo.

**Comment by Bitcoinera** [comment]
> No, it is reducing the perceived delay imo.

let's measure it chronometrically. Opinions won't get us far

**Comment by faboweb** [comment]
I agree. But put your chrome to load with 3G

**Comment by Bitcoinera** [comment]
Speed: Slow 3G

With loader (Infinity): 



👀 

Without it:




Didn't expect such dramatic results to be honest

**Comment by Bitcoinera** [comment]
I was wrong in the end 😅

**Pull request closed without merging**
