### PR TITLE
Fabo/use polkadot api signing

### PR DESCRIPTION
**Pull request by faboweb**
The signing didn't work on mainnet so I changed it to use the API signing which works. Also slims the code. Probably ripre for a refactor at some point

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f285c8ce05c4565b4f3bfd2--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
:eyes: 

Any idea why the API signing works and the FE not? :shrug:

**Comment by Bitcoinera** [comment]
I am still getting BatchInterrupted in production? Going to try now locally

**Comment by faboweb** [comment]
your getting batchinterrupted for a different reason. can you share the transaction?

**Pull request merged**
