### PR TITLE
Ana/upgrade akash to phase2

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

WIP because RPC endpoint is not working correctly (also a bit confusing with the public and the regular one to try this, inside the Network Object).

Waiting on Chinezu

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
We really should include in Simsala "Network upgrade" IMO

**Comment by faboweb** [comment]
🚀 Deployed on https://5efe2eb001304d5ecfecced6--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Something seems wrong with transactions... need to keep working on this upgrade

**Comment by Bitcoinera** [comment]
Waiting on endpoints from Forbole :pray:

**Comment by Bitcoinera** [comment]
It seems like there is always on the way...

**Comment by Bitcoinera** [comment]
Good to go! 💃 Just that the chain is stopped until next Monday, but looking good.

**Comment by jbibla** [comment]
`Publish on Netlify / e2e (pull_request)`?

**Comment by Bitcoinera** [comment]
> `Publish on Netlify / e2e (pull_request)`?

Mmm. Seems we need to release API

**Pull request merged**
