### PR TITLE
fixes for voting status bar

### LINKED ISSUE #4941: Align columns in Participant List in proposal overview
**Is your feature request related to a problem? Please describe.**

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jbibla**
closes #4941 and solves a few other issues

Screen Shot 2020-09-18 at 1 13 04 PM

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
let's actually have a graph showing the votes not the voting percentage

**Comment by faboweb** [comment]
🚀 Deployed on https://5f6502462cb5061c59aa8ff0--lunieio.netlify.app

**Review by faboweb — APPROVED** [review]

**Comment by Bitcoinera** [comment]
> let's actually have a graph showing the votes not the voting percentage

should we have a graph or a bar with different colors like in this design? https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/ew2r5p

**Comment by faboweb** [comment]
yes we should but we will follow up on that

**Pull request merged**
