### PR TITLE
WIP: Jordan/testing some SEO optimizations

### PR DESCRIPTION
**Pull request by jbibla**
Closes #ISSUE

**Description:**
- added vue-meta for better SEO and social graph (sharability)
- prerendering during build process for speed and SEO improvements
- viewport should be scalable on desktop (but not mobile)
- fixed overlapping tooltip issue in connected-network

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Is this PR ready?

**Comment by jbibla** [comment]
> Is this PR ready?

nope. still researching a proper prerendering implementation for social graph stuff.

**Comment by faboweb** [comment]
> nope. still researching a proper prerendering implementation for social graph stuff.

ok flagged it as WIP

**Comment by faboweb** [comment]
unit tests are failing

**Comment by jbibla** [comment]
closing this for now - will open a new simpler PR

**Pull request closed without merging**
