### PR TITLE
Benji/2234 enter submits forms

### LINKED ISSUE #2234: Pressing enter on action modals should submit forms
**Describe the bug**

Pressing enter on action modals should submit the form. Currently, it does not.

**To Reproduce**

- go to wallet page
- open send modal
- fill in empty form fields
- press `Enter`
- form is not submitted

**Expected behavior**

I would expect the form to be submitted.

**Additional context**

I believe this would be more semantic and accessible HTML.

### PR DESCRIPTION
**Pull request by thebkr7**
Closes #2234

**Description:**

Turned the password field into a form so that it is more accessible and now pressing enter submits the form. This is not implemented on any other section but only where the password is asked for. Will review Collins work on forms and the Action Modal and then implement if needed.

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by thebkr7** [comment]
Was the plan that any input field would click next or submit or only the final input field for the form would?

**Comment by colw** [comment]
I believe every input. 

So ideally, once the Modal appears it can be entirely keyboard driven:

1. Click Modal Open Action (whatever modal)
2. First input has focus
3. User types amount for example
4. User hits `enter` and the modal progresses to the next screen

- If the user presses escape, the modal disappears.

**Comment by faboweb** [comment]
very well explained @colw

**Comment by thebkr7** [comment]
Saving the current state is a good idea as writing a proposal to lose it all would be frustrating. I'll create an issue.

**Comment by thebkr7** [comment]
NOTE: Unfinished work. Not ready for review

**Pull request closed without merging**
