### PR TITLE
Ana/add bondedStake query to API

### PR DESCRIPTION
**Pull request by Bitcoinera**
Related to #4739 
**Description:**

The API PR to fix the problem of purgatory invisible stake in Polkadot/Substrate

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
image

**Comment by Bitcoinera** [comment]
Query to test:

```
query proposals {
 bondedStake(networkId:"polkadot-testnet", address:"5EZjN7ZD6hLN9wLGju8Uzu4NjXtTFhCpS8wUAxVdvTGEQaQY") {
  total
  active
  unlocking
  stale
}
}
```

It still needs to wait for 1h in order for the era in Westend to pass.

Some considerations: in the beginning I thought of making a query only for the unnominated/stale bonded stake, but then I thought that having all this data already there, in stakingLedger, it wouln't make sense adding this as well.

The advantage is that we can also add the `totalBonded` row once we merge this one. In Cosmos networks we already have this info coming from balance (just need to do total - available). Or, if you prefer, we can also subtract `unlocking` there :shrug: for Cosmos

**Comment by faboweb** [comment]
What do we need this for? We already have the staked tokens implied in the balances query.

**Comment by Bitcoinera** [comment]
> What do we need this for? We already have the staked tokens implied in the balances query.

The original idea was getting the stale bonded balance. It is explained in the issue. We were discussing this in the meeting too: users can have bonded but unnominated balance/stake, Polkadot allows this. In Lunie, these balances won't just show.

But to get this stale bonded we need a new query. Would be bad practice to have it in FE

**Comment by faboweb** [comment]
> In Lunie, these balances won't just show.

This is not true. We are displaying liquid stake. Ergo bonded stake is `total stake - liquid stake`. Even if display this explicit, we don't need another query for that.

**Comment by Bitcoinera** [comment]
> This is not true. We are displaying liquid stake. Ergo bonded stake is `total stake - liquid stake`. Even if display this explicit, we don't need another query for that.

I think it give people more comfort to see that their tokens are somewhere. If they see total but then don't see any delegation, they can easily get scared. I know what I'm saying since I have been in this situation.

About calculating with `total stake - liquid`, the problem is that you need to search for staked with no nomination... Unless I am missing something here

**Comment by faboweb** [comment]
> About calculating with total stake - liquid, the problem is that you need to search for staked with no nomination... Unless I am missing something here

you can search using `stakingDenom` right?

**Comment by Bitcoinera** [comment]
> you can search using `stakingDenom` right?

What do you mean?

**Comment by Bitcoinera** [comment]
Good bye, my sweet PR! :hand:

**Pull request closed without merging**
