### PR TITLE
WIP Ana/4476 bring back push notifications

### PR DESCRIPTION
**Pull request by Bitcoinera**
Related to #4476

**Description:**

The code for push notifications is back! :tada:

Guess I need to test it on mobile. For starters there is this  `PUSH_NOTIFICATIONS_FRONTEND_URL` variable set as `https://app.lunie.io`... but shouldn't it be set to be the app link? Aren't we running into the same issue we had with the magic links here again, that we need to host the app on Firebase? I don't know :shrug: 

Maybe a proxy on Firebase would do the job? (Tentative comment)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f0b65f75b768eba9760c9ee--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
What is left: session module and try this with Android Studio / Bitrise

**Comment by faboweb** [comment]
I will pick some things from this but use the new notification system for this to reduce the code surface.

**Comment by Bitcoinera** [comment]
> I will pick some things from this but use the new notification system for this to reduce the code surface.

Makes sense

**Comment by Bitcoinera** [comment]
Opening as a reference

**Comment by Bitcoinera** [comment]
Closing in favor of #4608

**Pull request closed without merging**
