### PR TITLE
Fix TmDataLoading component registration in PageValidator

### LINKED ISSUE #3292: Incorrect TmDataLoading component registration in PageValidator
**Describe the bug**
Incorrect TmDataLoading component registration in PageValidator

**To Reproduce**

1. Go to `/validators/cosmosvaloper1et77usu8q2hargvyusl4qzryev8x8t9wwqkxfs`
2. You will see error:

```
[Vue warn]: Unknown custom element: <TmDataLoading> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3292 

**Description:**

- Fix TmDataLoading console error in PageValidator
- Fix TmPage loading bug

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by colw** [comment]
Technically it's not wrong, but I'm assuming we don't want this :)

Screenshot 2019-12-13 at 13 34 49

**Comment by faboweb** [comment]
TmPage is handling the loading state already by setting the `loading` attribute. I think `<TmDataLoading v-if="$apollo.queries.validator.loading" />` should probably be removed.

**Comment by mariopino** [comment]
> TmPage is handling the loading state already by setting the `loading` attribute. I think `<TmDataLoading v-if="$apollo.queries.validator.loading" />` should probably be removed.

mmm problem is here again when using TmPage loading attribute instead of TmDataLoading.

**Comment by colw** [comment]
My thoughts are the page should not handle the loading display, but the components _inside_ the page. This way we render as quickly as possible, and we do not block the page based on one piece of information being slow.

**Comment by mariopino** [comment]
> My thoughts are the page should not handle the loading display, but the components _inside_ the page. This way we render as quickly as possible, and we do not block the page based on one piece of information being slow.

That make sense, but the loading property in TmPage is provided by the child component, what is the difference?

**Comment by mariopino** [comment]
> > TmPage is handling the loading state already by setting the `loading` attribute. I think `<TmDataLoading v-if="$apollo.queries.validator.loading" />` should probably be removed.
> 
> mmm problem is here again when using TmPage loading attribute instead of TmDataLoading.

Ok, was a problem with loading property in TmPage, it was using a non existent variable to show TmDataLoading,  it's fixed now.

**Pull request merged**
