### PR TITLE
Colw/bundle analyzer

### PR DESCRIPTION
**Pull request by colw**
**Description:**

- Create a `dist/bundle_sizes.html` report outlining dependency sizes.
- Update dependencies

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
The path is bad as the files would be copied to the hosting location

**Comment by faboweb** [comment]
I think there is an option to do bundle analyzing as a command line thing instead of bundling it into the build process.

**Comment by colw** [comment]
On hold. Finding solution to create report, but not upload this to S3.

**Comment by faboweb** [comment]
I think vue-cli has this already integrated: https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build

**Comment by colw** [comment]
> I think vue-cli has this already integrated: https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build

🤦‍♂

**Pull request closed without merging**
