### PR TITLE
Ana/possible fix for stagnant networks balances

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

@faboweb can you try this and see if your problem persists?

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
I think first we need to reproduce

**Comment by Bitcoinera** [comment]
> I think first we need to reproduce

Yes, sure. I though you were able to reproduce at least the stagnant balances, that's why I asked you

**Comment by faboweb** [comment]
No, sorry. Not 100% sure how. If it happens again I will try to document.

**Comment by Bitcoinera** [comment]
What the user describes is like the error with the ActionModal open across networks but like not having it open. Will have another look at the conversation if he provided some new info

**Comment by Bitcoinera** [comment]
OK, will close this for now as we are not able to reproduce the error and it seems the user solved it by himself 🤷

**Pull request closed without merging**
