### PR TITLE
Ana/add loadMore logic to ParticipantList

### LINKED ISSUE #4903: Add Pagination or cascade loading to Voters in the new PageProposal component
Not critical but nice to have. Some proposals have hundreds and hundreds of voters

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4903 

**Description:**

I see it loads the voters in batches, but I think it should be the user clicking on a `Load More` thing who activates this. Otherwise we have the same issue than before, too many voters. Do you agree?

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
yeah, just show 5 with a load more button (centered) - if a user clicks, show 5 more

**Comment by Bitcoinera** [comment]
It's ready. Looking like this:

image

**Comment by faboweb** [comment]
let's finish this merge it in and add another PR to follow up with filtering in the API?

**Comment by Bitcoinera** [comment]
> let's finish this merge it in and add another PR to follow up with filtering in the API?

What do you mean with filtering in the API? Filtering participants? I don't understand.

This PR is already finished. Only the tests getting blocked. Will merge with develop and see if the new actions version works better

**Comment by faboweb** [comment]
🚀 Deployed on https://5f61d84219eca59fc5ffc275--lunieio.netlify.app

**Comment by faboweb** [comment]
> What do you mean with filtering in the API? Filtering participants? I don't understand.

I am referencing Jordan: > really seems like this should be implemented on the API side. no point in loading 1000s of voters if we are only showing 5.

**Comment by jbibla** [comment]
gahhhh e2e is so unreliable

**Review by jbibla — APPROVED** [review]

**Comment by Bitcoinera** [comment]
> I am referencing Jordan: > really seems like this should be implemented on the API side. no point in loading 1000s of voters if we are only showing 5.

I think it is fine this way. No such an impact on performance, I think. And we can load voters immediately on FE. More handy

**Pull request merged**
