### PR TITLE
Jordan/toggle

### PR DESCRIPTION
**Pull request by jbibla**
the new proposal page has a toggle component in it. the validator list already has a toggle feature but it should be componentized so we can use it in a few places. also, updating for the new designs from our guy charlie.

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f1e3645b5e2490ae0753a13--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Not looking bad!

image

**Comment by faboweb** [comment]
Didn't you say you want to remove popular from the toggle?

**Comment by Bitcoinera** [comment]
I actually prefer Mario's toggle, sorry :sweat_smile: I like the colors and being more round

**Comment by jbibla** [comment]
> Didn't you say you want to remove popular from the toggle?

yep we should but not in this PR

**Comment by Bitcoinera** [comment]
> > Didn't you say you want to remove popular from the toggle?
> 
> yep we should but not in this PR

Nooo, my work :crying_cat_face:

Why did you change your mind? You mean completely removing the whole popular logic?

**Comment by jbibla** [comment]
> You mean completely removing the whole popular logic?

popular should be a column with sorting functionality, not a toggle button. so no, not exactly removing the whole logic.

**Comment by faboweb** [comment]
... and filtering out the validators without identity should be a checkbox. But I guess we need to iterate over the concept a little.

**Comment by Bitcoinera** [comment]
> popular should be a column with sorting functionality, not a toggle button. so no, not exactly removing the whole logic.

This is how I started Popularity actually, no kidding. I put a star on every ceiling of that column :star_struck:

**Comment by jbibla** [comment]
yes yes go away stalebot

**Comment by jbibla** [comment]
i will finish this!

**Pull request closed without merging**
