### PR TITLE
Aleksei/e2e retries

### PR DESCRIPTION
**Pull request by iambeone**
Closes #ISSUE

**Description:**

add retries to e2e tests

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
feels like a bandaid - what problem is this solving?

**Comment by iambeone** [comment]
Sometimes something is failing during e2e. For example browserstack and tests are passing on rerun.

**Comment by jbibla** [comment]
> Sometimes something is failing during e2e.

lol yeah I know. but retrying isn't directly addressing the problem. 

we can merge for now but we should figure out why e2e is unreliable.

**Comment by faboweb** [comment]
> we can merge for now but we should figure out why e2e is unreliable.

I absolutely agree

**Pull request merged**
