### PR TITLE
Update to logo path, project name, typo in TmSessionWelcome

### LINKED ISSUE #2515: Logo path, project name, typo needs updating
**Describe the bug**
1. Logo path in README.md
2. Project name in CONTRIBUTE.md
3. Typo in TmWelcomeSession (text "loose" should be "lose", and is only visible on testnet.lunie.io)

**To Reproduce**
(For 3.)
1. Go to testnet.lunie.io
2. Click on "Sign In" button

**Expected behavior**

Expect "You could loose all your money." to be "You could lose all your money."

### PR DESCRIPTION
**Pull request by gin**
Closes #2515 

**Description:**
- Updated logo's path in README.md
- Updated project's name to "Lunie" in CONTRIBUTE.md
- Fixed typo in TmSessionWelcome

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
@faboweb any idea what's up with CircleCI?

**Comment by faboweb** [comment]
Circle has issues with PRs from foreign repos. I write them.

**Comment by faboweb** [comment]
Hey @gin, could you trigger the CI again by pushing any commit?

**Comment by gin** [comment]
👍 Tests passed but `Exited with code 255`
```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter upload-coverage [flags]

Flags:
  -s, --batch-size int    batch size for source files (default 500)
  -e, --endpoint string   endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -r, --id string         reporter identifier
  -i, --input string      input path (default "coverage/codeclimate.json")
      --insecure          send coverage insecurely (without HTTPS)

Global Flags:
  -d, --debug   run in debug mode
```

**Comment by faboweb** [comment]
Thanks @gin for your contribution and for being a guinea pig for contributions! :)

**Pull request merged**
