### PR TITLE
Jordan/portfolio loading

### LINKED ISSUE #3225: portfolio page should load more gracefully
**Is your feature request related to a problem? Please describe.**

the portfolio page in the web and on mobile loads too slowly. in addition to this, we load an empty portfolio first, instead of a loading screen.

**Describe the solution you'd like**

- the user should never see the empty portfolio screen if the they have a balance, rewards, and a portfolio of validators
- the page should also load faster

**Describe alternatives you've considered**

- we have a placeholder graphic we could use here

**Additional context**

- the way this works now causes anxiety and confusion. it would be better for the user to be annoyed by a loading graphic than worried about their balance or portfolio if that needs to be the first step.

### PR DESCRIPTION
**Pull request by jbibla**
Closes #3225

**Description:**
- added graceful loading to portfolio page (super easy, should be on every page)
- new designs for bars with less code complexity
- fixed minor style bug with disabled inputs

Screen Shot 2019-12-04 at 12 44 36 PM
Screen Shot 2019-12-04 at 12 44 46 PM

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [x] Attach screenshots of the UI components on the PR description (if applicable)

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Pretty cool!

**Comment by faboweb** [comment]
Design doesn't match 100% so there is some jumping, but a leap improvement

**Comment by faboweb** [comment]
And there is a delay even before the portfolio shows

**Comment by faboweb** [comment]
https://www.loom.com/share/fd6d6f76a75149dea83ee9b75d6442f1

**Comment by jbibla** [comment]
> And there is a delay even before the portfolio shows

yep. this is our bundle being enormous. i'm not sure how to render the placeholder loader earlier than in the component we want to "place-hold"

**Comment by colw** [comment]
This is awesome. Nice work.

I wonder though, if using empty divs+css (without the svgs) would be quicker?

**Comment by faboweb** [comment]
Note: we might switch later to just use css

**Comment by jbibla** [comment]
> I wonder though, if using empty divs+css (without the svgs) would be quicker?

this is probably a better approach

**Pull request merged**
