### PR TITLE
Ana/4991 fix loader keeps appearing on transactions page

### LINKED ISSUE #4991: Loader keeps appearing on Transactions Page
When scrolling down, the loader keeps appearing, although there are no more transactions to load. The Eventlist component `loadMore` logic must be somehow broken 

Peek 2020-09-24 20-19

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4991 

**Description:**

Look good although it can likely be improved. There is a second time where the loader opens for less than a second

Peek 2020-09-26 16-27

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
There is also a duplicated keys error, but it only happens using this account (akash1lhenngdge40r5thghzxqpsryn4x084m9jkpdg2) in akashnet-1 :shrug: Quite an edge case there

**Comment by faboweb** [comment]
🚀 Deployed on https://5f6f50b0879ac78f10d43677--lunieio.netlify.app

**Comment by jbibla** [comment]
i don't really get this. does this page use infinite loader or something? are using a `loaded` property?

**Comment by Bitcoinera** [comment]
> does this page use infinite loader or something? are using a `loaded` property?

Yes, EventList use infinite scroll, if this is what you mean. And no, it is not using `loaded` but `moreAvailable` to signal when it should stop loading more transactions

**Review by jbibla — APPROVED** [review]

**Pull request merged**
