### PR TITLE
Ana/regen integration

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**
I basically added here the icon for the Regen network. Not too much needed to be done regarding integration, as I suspected.

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Mmm, I need to fix how balances are shown. I confirmed yesterday evening that SEED is a different token. Don't merge this yet please :pray:

**Comment by faboweb** [comment]
There is little to merge :D

**Comment by colw** [comment]
> Mmm, I need to fix how balances are shown. I confirmed yesterday evening that SEED is a different token. Don't merge this yet please 🙏

You could put it in a different PR as it seems unrelated. Up to you 👍

**Comment by Bitcoinera** [comment]
Ok, let's leave this one as it is and I will make another branch for the balance fix

**Pull request merged**
