### PR TITLE
Revert back to before sidecar

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Try to fix the CORS hell we have gotten into

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
? Didn't work??

**Comment by faboweb** [comment]
🚀 Deployed on https://5f7658c5bf48a000e6ec2962--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Weird

**Comment by Bitcoinera** [comment]
Tested and works great

**Comment by Bitcoinera** [comment]
Closed in favor of #5025

**Pull request closed without merging**
