### PR TITLE
Ana/add muon token icon

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Adds the icon for MUON (which is, suprise! the same than for ATOMs)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
File is named uon

**Comment by Bitcoinera** [comment]
> File is named uon

Yes, that is how it works. And ATOM one is named tom.png

**Comment by faboweb** [comment]
that's stupid. lets change that. @jbibla was that intentional?

**Comment by Bitcoinera** [comment]
xD

**Pull request merged**
