### PR TITLE
Fabo/persist cache

### PR DESCRIPTION
**Pull request by faboweb**
Adds an apollo cache to local storage persistence

### CODE REVIEW

**Comment by faboweb** [comment]
Hot hot hot 🐎 🔥

**Comment by iambeone** [comment]
Dangerous thing...

**Comment by faboweb** [comment]
Why dangerous?

**Comment by Bitcoinera** [comment]
Will this have any effect on our chunks issue?

**Comment by iambeone** [comment]
We can't manage this cache, so we can't rely on it) But the only issue i have noticed is with activity page, it doesn't show latest transactions

**Comment by faboweb** [comment]
@Bitcoinera no I don't think so
@iambeone ok let's check why. And I think we can still manipulate that cache I guess.

**Comment by iambeone** [comment]
I have made two stake and the first one appears in activity, but not the second

**Comment by faboweb** [comment]
Does the request still happen? What's the result of the request?

**Comment by Bitcoinera** [comment]
> But the only issue i have noticed is with activity page, it doesn't show latest transactions

Remember that we still have that bug that is probably preventing `subscribeToMore` from working... So maybe that is why.

This needs to be fixed before testing: #3700

**Comment by faboweb** [comment]
I confirm the activity issue. let's check if the update works.

**Comment by faboweb** [comment]
I also got issues with networks preloading

**Comment by iambeone** [comment]
This issue is fixed (i will make a pr today), but you can try to update the page and activity page will remain the same

**Comment by Bitcoinera** [comment]
Yes, Aleksei and me were discussing about this PR and the only thing we could come up for now is having a `localStorage.clear()` in ActionManager to handle new transactions.

Still, if this happens in Activity I bet it happens with rewards and validators too... so it seems quite unsafe (and putting `localStorage.clear()` everywhere kind of defeats the purpose too).

We could research if there is a way we can better control this cache. But probably not using localStorage.

**Comment by faboweb** [comment]
hmm ok. I am doubting a bit that this is an unsolvable problem.

**Comment by faboweb** [comment]
Can you recheck this PR. Seems to work fine.

**Comment by Bitcoinera** [comment]
Oh God!!!

We need to merge this!!! It's A-M-A-Z-I-N-G!!

I just tried and it is boosting the performance like nothing else! This is this week's PR I'd say xD

And yeah, working like a charm.

So fast!

**Pull request merged**
