### PR TITLE
Atharva/fixes #2966 `url for "activity" still points to "transactions"`

### LINKED ISSUE #2966: url for "activity" still points to "transactions"
**Describe the bug**

The URL for the activity page is accessed via `/transactions`.

**Expected behavior**

- redirect `/transactions` to `/activity`
- add default route / URL for Activity to be `/activity`

### PR DESCRIPTION
**Pull request by atharva3010**
Closes #2966 

**Description:**

- redirects `/transactions` to `/activity`  
- added default route / URL for Activity to be `/activity`

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Instead of redirecting the `/transactions` route to `/activity` we should change all occurences of `/transactions` so the code stays clean.

**Comment by faboweb** [comment]
And you need to run `yarn changelog` to document your changes ;)

**Comment by atharva3010** [comment]
Sure! I’ll do that.

**Comment by atharva3010** [comment]
I was a bit confused as the issue #2966 clearly specified for the redirect so, I assumed that modifying the occurrences wasn’t needed. No worries!

One question, will the redirect still be needed? Even after replacing all occurrences of `/transactions` with `/activity`? Are there any external links which may point to `/transactions`?

Do we also need to change the component name too? Currently it’s `PageTransactions`

**Comment by atharva3010** [comment]
@faboweb please check now

**Comment by jbibla** [comment]
a redirect from transactions is a good idea @faboweb - there may be bookmarks and links. i'd rather we don't break the links.

**Comment by jbibla** [comment]
can we avoid the commits that are just spacing changes (from a linter)?

**Comment by atharva3010** [comment]
@jbibla
> can we avoid the commits that are just spacing changes (from a linter)?

We can certainly avoid them, but I think we should keep code linted and formatted.

**Comment by jbibla** [comment]
@atharva3010 - i'm in favour of linting! just want to be sure our lint config is working as expected and these changes won't be reverted by someone else who has a different lint config.

@faboweb shouldn't all the files be linted already? if not, can we lint 'em all?

**Comment by atharva3010** [comment]
@jbibla oh okay! No worries. I don’t have a global lint config, I have linted the code with the lunie workspace config.

**Comment by faboweb** [comment]
I could imagine we don't have an explicit rule for some spacings. Let's add the rule to avoid those irrelevant changes.

**Comment by faboweb** [comment]
Did you consider the URLs in `test/e2e/`? (the redirect would still work I guess, but would be cleaner to change them as well)

**Comment by atharva3010** [comment]
@faboweb I guess I haven’t changed anything in the tests, I will change them too :)

**Comment by jbibla** [comment]
yep! let's get this merged!

**Pull request closed without merging**
