### PR TITLE
[Simsala] automatic release created for v1.0.0-beta.119

### PR DESCRIPTION
**Pull request by faboweb**
Please manually test before merging this to master

### Added

- [#2928](https://github.com/cosmos/lunie/pull/2928) Add Network page with a slection of different networks to select @colw
- [#2947](https://github.com/cosmos/lunie/pull/2947) Ability to filter validator list by name or jailed status @colw
- [#2670](https://github.com/cosmos/lunie/issues/2670) Add "max" button to amount fields #2670 @mariopino

### Changed

- change the lunie logo to include wordmark @jbibla

### CODE REVIEW

**Comment by jbibla** [comment]
i don't see the networks link in the netlify link... do you guys?

**Comment by faboweb** [comment]
> i don't see the networks link in the netlify link... do you guys?

It's hidden behind the experimental flag. Should we enable it right away?

**Comment by jbibla** [comment]
> Should we enable it right away?

what are we waiting for? does it work on the testnet?

**Comment by faboweb** [comment]
Apparently it's buggy

**Pull request merged**
