### PR TITLE
[WIP] Fix Polkadot e2e tests

### LINKED ISSUE #4576: Failing polkadot e2e tests
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #4576 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f19f1bf4603358b70c2b2a5--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
I can also help here, or directly overtake it if needed

**Comment by jbibla** [comment]
do we know what the problem is yet?

**Comment by Bitcoinera** [comment]
> do we know what the problem is yet?

Something in the recover account flow

**Comment by Bitcoinera** [comment]
I guess we can close this for now until we have some more time to fix this

**Pull request closed without merging**
