### PR TITLE
[Simsala] automatic release created for app-v1.0.233

### PR DESCRIPTION
**Pull request by faboweb**
Please manually test before merging this to master

### Added

- [#5143](https://github.com/cosmos/lunie/issues/5143) Add Show Seed feature to UserMenu @Bitcoinera
- [#5117](https://github.com/cosmos/lunie/issues/5117) Lunie supports now IOV starnames @faboweb

### Changed

- [#5098](https://github.com/cosmos/lunie/issues/5098) Make possible for MaintenanceBar to be network specific @Bitcoinera
- [#5119](https://github.com/cosmos/lunie/issues/5119) Don't encourage proposal creation for Polkadot networks @Bitcoinera
- [#5147](https://github.com/cosmos/lunie/pull/5147) Some little improvements from suggestions regarding the Manage address feature on UserMenu @Bitcoinera
- remove intercom capacitor from mobile to resolve build issue @jbibla
- bump capacitor version @jbibla
- [#5127](https://github.com/cosmos/lunie/issues/5127) Update polkadot-js/api to release v2.3.1 @mariopino

### Fixed

- [#4989](https://github.com/cosmos/lunie/pull/4989) Fix vote display on PageProposal @Bitcoinera

### Deprecated

- [#5114](https://github.com/cosmos/lunie/pull/5114) Remove unused publish.sh from tasks folder @Bitcoinera

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f9334cd72e1523b23c99f06--lunieio.netlify.app

**Review by jbibla — CHANGES_REQUESTED** [review]
the seed experience needs a bit more love

- still appears in the list after being deleted

**Comment by faboweb** [comment]
> still appears in the list after being deleted

fixed

**Comment by jbibla** [comment]
looks good to me

**Comment by Bitcoinera** [comment]
> looks good to me

Unit tests are failing

**Comment by jbibla** [comment]
unit tests are passing... what do you mean @Bitcoinera ?

Screen Shot 2020-10-28 at 8 52 47 AM

**Comment by Bitcoinera** [comment]
> unit tests are passing... what do you mean @Bitcoinera ?

Because I just fixed them :stuck_out_tongue: Look at the last commit

**Comment by jbibla** [comment]
lol ok thanks

**Review by Bitcoinera — APPROVED** [review]

**Pull request merged**
