### PR TITLE
Ana/fix navigation duplicated in recover flow

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

One of those magic moments when the solution is actually deleting code :champagne: 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
so what happens if you click the network item now?

**Comment by faboweb** [comment]
🚀 Deployed on https://5f230095a3eb0cf1b6208253--lunieio.netlify.app

**Comment by faboweb** [comment]
the click is handled by networklist not  by networkitem

**Comment by Bitcoinera** [comment]
> so what happens if you click the network item now?

in Networks it will work but in both create and recover flows will fail with a Navigation duplicated error.

The strange thing is that we didn't notice this happening yesterday :thinking:

**Comment by Bitcoinera** [comment]
Let's still merge this one in develop? Or should we pull from master to develop instead? What is the best flow?

**Pull request merged**
