### PR TITLE
Ana/fix waiting for extension button

### LINKED ISSUE #3306: Waiting for extension button doing weird things
**Describe the bug**

Sometimes, when the Delegation modal grows in height to cover the whole screen, the `Waiting for extension` button will behave strangely, the fonts shifting to the right and the button itself staying on its correct position. 

**To Reproduce**

Just initiate a delegation and play with the screen size until you see this happening.

**Expected behavior**

The text should stay centered within the button
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Brave 
 - Version: v1.1.20, Chromium 79.0.3945.74 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3306 

**Description:**

Just a simple fix for a simple issue.

Fixes the "Waiting for Extension" captions overflow in the ActionModal:

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
thanks for trying to fix this so quickly. this isn't the right fix for this though, because this will only solve the problem for this button this one time. it's an issue with the button styling in general which should be resolved.

first, we need to understand what is causing this?

**Comment by Bitcoinera** [comment]
> it's an issue with the button styling in general which should be resolved.
> 
> first, we need to understand what is causing this?

Yes, I agree. Will have a look

**Comment by Bitcoinera** [comment]
OK, done! It was a simple fix in `TmButton` itself. Adding `width: auto` did the trick

**Comment by jbibla** [comment]
why are unit tests failing?

**Comment by Bitcoinera** [comment]
> why are unit tests failing?

Fixed

**Comment by faboweb** [comment]
If you checked the coverage and the things needed to be covered are not important you can merge

**Comment by jbibla** [comment]
the coverage is supposed to demonstrate a change ... but css shouldn't change the calculation of test coverage before and after?

**Comment by Bitcoinera** [comment]
> the coverage is supposed to demonstrate a change ... but css shouldn't change the calculation of test coverage before and after?

Yes, it is quite strange that it did change. Cannot wrap my head around it :woman_shrugging:

**Pull request merged**
