### PR TITLE
WIP Fabo/app testing

### PR DESCRIPTION
**Pull request by faboweb**
Android app is opening in Browserstack but the test is failing still

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5ef365911967d7021c54f4df--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Is this still a problem?

**Comment by faboweb** [comment]
yes, we still want to be sure we don't publish broken apps

**Comment by Bitcoinera** [comment]
> yes, we still want to be sure we don't publish broken apps

ah ok, now I remember what this is about

**Comment by jbibla** [comment]
this is indeed a stale PR. fabo will re-open when he can work on this again.

**Pull request closed without merging**
