### PR TITLE
Update proposals every new block

### LINKED ISSUE #3277: proposals page never refreshes
**Describe the bug**

- the proposal page will only load once per session
- this means you have to refresh the page to see new proposals
- on mobile, this means you have to refresh the app 

**Expected behavior**

- every block we should fetch proposals
- every x number of blocks we should poll for proposals
- whenever there is a new proposal we should push this data to lunie

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3277

**Description:**

Update proposals every new block in PageProposals.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by mariopino** [comment]
Should we need to do the same with single proposal page?

**Comment by jbibla** [comment]
why not every block when you're on PageProposal?

**Comment by mariopino** [comment]
> why not every block when you're on PageProposal?

Hey @jbibla I tried it every block but It's a bit annoying to see the data loading every 6 seconds, so decided to reload it every 10 blocks.

Best solution would be a proposal subcription then FE would get notified when a new proposal arrives (just like you proposed in the issue).

**Comment by jbibla** [comment]
ok cool. i understand. 

the way we should solve the problem you're mentioning is to use a `loaded` property. after the first `loading` is done, we set `loaded` to true and then the page will not rerender, but the data will update (vue takes care of this).

**Comment by mariopino** [comment]
> ok cool. i understand your thinking now!
> 
> the way we should solve the problem you're mentioning is to use a `loaded` property. after the first `loading` is done, we set `loaded` to true and then the page will not rerender, but the data will update (vue takes care of this). `TmPage` has this logic in place.

Aaam yes. that's the behaviour I was looking for. I'll change it to use the loaded logic ...

**Comment by mariopino** [comment]
Ready to merge finally (I hope) :-)

**Pull request merged**
