### PR TITLE
Fabo/polkadot caches cross chains

### PR DESCRIPTION
**Pull request by faboweb**
The cache was only for Kusama

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Shouldn't the script include a way to generate the folder `networkId-caches` if it doesn't exist yet?

I got this error after running the script:

```
(node:9549) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ana/lunie/lunie/api/kusama-caches/eras.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at storeEraData (/home/ana/lunie/lunie/api/scripts/getOldPolkadotRewardEras.js:41:6)
    at main (/home/ana/lunie/lunie/api/scripts/getOldPolkadotRewardEras.js:314:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This means we need to take it into account when deploying this in our instances (manually creating the folder).

**Comment by faboweb** [comment]
true! fixing it, sorry

**Comment by Bitcoinera** [comment]
Missing changelog :stuck_out_tongue:

**Comment by Bitcoinera** [comment]
Now I got this but guess this is expected? Am I missing some kind of env variable in `scriptRunner`? 

Ah HASURA_URL, right

```
(node:9813) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:8080/v1/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:8080
    at ClientRequest.<anonymous> (/home/ana/lunie/lunie/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by faboweb** [comment]
changelog is in scriptRunner dir. The script should probably move there

**Pull request merged**
