### PR TITLE
WIP: Ana/livepeer handle getselfstake separately

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**
This PR should fix, together with the PR with the same name for the API (#238), the problem of the slow loading of validators in Livepeer.

The big issue I have encountered here is that it is kind of hard to handle Objects as inputs in GraphQL. So that is why this PR is a work in progress. I don't know how to write the `selfStake` query in `PageValidator` to allow a validator Object as a parameter.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
Have you considered handling everything on the server side?
Re object as parameter: You can just pass an ID and look for the object on the server side by using this ID.

**Comment by Bitcoinera** [comment]
> Have you considered handling everything on the server side?
> Re object as parameter: You can just pass an ID and look for the object on the server side by using this ID.

But then we would still to update the query every now and then, no? And it is what goes slow.

Maybe I didn't get fully what you propose...

**Comment by Bitcoinera** [comment]
It is still unclear to me how to handle this

**Comment by faboweb** [comment]
> But then we would still to update the query every now and then, no? And it is what goes slow.

yes and I would solve, why the query is slow from the API. something I would try:

- load validators per block into the store
- asynchronously load the selfStake also in the store (adding it to the validator object)
- if updating the selfStake takes too long, thottle the selfStake updates to every x blocks

**Comment by Bitcoinera** [comment]
Put in the freezer for now

**Pull request closed without merging**
