### PR TITLE
Fabo/fix css hot reloading

### PR DESCRIPTION
**Pull request by faboweb**
Closes #ISSUE

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Really strange. I see the hotModuleReplacement.js message in the console but still not loading the styles directly. I need to do a soft refresh... something else is also broken?

**Comment by Bitcoinera** [comment]
🤷‍♀

**Comment by jbibla** [comment]
whoops. sorry ana. 

can you check again on develop now? works perfectly for me.

**Comment by Bitcoinera** [comment]
Ah don't worry Jordan. The shrugging emoji was just to mean, "why it doesn't work for me?"

But I just tried and now it does. Yeey!

**Pull request merged**
