### PR TITLE
[Simsala] automatic release created for v1.0.0-beta.86

### PR DESCRIPTION
**Pull request by faboweb**
Please manually test before merging this to master <a href='https://8217-99653950-gh.circle-artifacts.com/0/tmp/voyager/dist/index.html'>here</a>

### Fixed

- added git config to circleci config to stop failing mergebacks @jbibla

### CODE REVIEW

**Comment by jbibla** [comment]
`pendingUpdate failed`

also, did you close https://github.com/luniehq/lunie/issues/2271 ?

**Comment by faboweb** [comment]
> pendingUpdate failed?

there are no updated here. so this check should fail

> also, did you close #2271 ?

no, why?

**Comment by jbibla** [comment]
> Please manually test before merging this to master here

are you adding this manually?

**Comment by faboweb** [comment]
> are you adding this manually?

No that is automatic. But #2271 is about doing this for every PR.

**Comment by jbibla** [comment]
ah ok! got it.

**Pull request merged**
