### PR TITLE
Ana/fix header pageproposals

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

Here I add `TmBalance` to `PageProposals.vue`, which I accidentally removed earlier.
So it shows again the header with the balance in the proposals page. 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by jbibla** [comment]
we should not display the balance header on page proposals.

**Comment by faboweb** [comment]
Fixed in #3221

**Comment by Bitcoinera** [comment]
It was just a misunderstanding :sweat_smile:

**Comment by faboweb** [comment]
no problem ^^

**Pull request closed without merging**
