### PR TITLE
WIP Ana/add voting chart page proposal

### LINKED ISSUE #4990: Display relevant voting data on PageProposal (vote option percentage). Add beautiful chart
Issue for #4980

Leaving this open so we don't forget about this super relevant matter. As important as #4988 

Right now the ProgressBar on PageProposal for voting period only displays the percentage of circulating tokens that voted on that proposal. This is not relevant. People would like to know instead what percentage of Yes, No and so on there is.

Another option: display the percentage on the Vote Option Card itself and keep the progress bar as it is :shrug: I don't like this option that much though:

Charlie's design is cool: https://www.sketch.com/s/8ffba04e-5055-44dd-984c-c60a74f5103b/a/DApAG4

We could do our own multi-color ProgressBar to accomplish that design

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4990 
**Description:**

Should I go on? Need to make colors dymanic:

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
I think it is a good idea to have something like this :star_struck:

**Comment by faboweb** [comment]
🚀 Deployed on https://5f6a3d684a73fd1f4897cadd--lunieio.netlify.app

**Comment by Bitcoinera** [comment]
Please, don't close this. Let's discuss possible implementations, but let's do this (I know, not super priority but easy & great to have)

**Comment by Bitcoinera** [comment]
Closing for now as I was requested to do, but leaving open inside my heart :heart:

**Pull request closed without merging**
