### PR TITLE
Aleksei/account creation fix

### PR DESCRIPTION
**Pull request by iambeone**
Closes #ISSUE

**Description:**

Commented an isTestnet function logic due to wrong account creation behavior

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
What's the exact issue here?

**Comment by iambeone** [comment]
The one with showing the account name window on account creation flow in secure mode

**Comment by faboweb** [comment]
And why does this fix it?

**Comment by iambeone** [comment]
For some reason (i don't know why) account name step is shown if current network is a testnet. Probably it was made for a reason, but not finished. I have updated this function to always return false, just to keep someone's work. Maybe we will enable account creation for testnets in future

**Comment by faboweb** [comment]
so the issue is that the intended functionality is: if this is a testnet allow account creation. I think @Bitcoinera worked on that. Instead of this hack, can we fix that this intended functionality is not working?

**Comment by Bitcoinera** [comment]
> Instead of this hack, can we fix that this intended functionality is not working?

OK, let me take over. I'm going to look into it

**Comment by iambeone** [comment]
If we need to do it right now, why not)

**Comment by Bitcoinera** [comment]
OK, now it is all working as expected. I also tested the mainnets and trying copy pasting the link and it would go to the InsecureModeWarning component as expected.

I don't know how all those InsecureModeWarnings got into the flow (TmSessionSignUpPassword and TmSessionSignUpSeed) but definitely not necessary and causing this bug.

Yes, this solution consisted of actually deleting code! 🍾 

Let's celebrate

**Pull request merged**
