### PR TITLE
Ana/add nite mode

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #ISSUE

**Description:**

OK, I know now you will say "oh, but you should have waited on designs and we should have discussed this and...". So maybe I'm just a masochist or something like that.

But adding this took me nearly no time and it is a super nice feature I already requested since we introduced the light themes. Plus I really invested no time in styling (since I know there are going to be changes for sure)

This is how it is looking now:

image

I call the other one DayMode. I find it kind of poetic:

image

NOTE: Somehow regular unicode emojis are not "working" for me on my Ubuntu :shrug: That is why they look so... bare 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f0467d6da61d10752dcedd5--lunieio.netlify.app

**Comment by jbibla** [comment]
you should have waited on designs and we should have discussed this

**Comment by Bitcoinera** [comment]
> even though i really think this is unimportant ...

Thank you so much for your feedback Jordan! I really like it what you propose here, a much more elegant solution!

As this is quite down below in the list, I will prio everything else and come back to this PR when I find everything else finished :+1

**Comment by Bitcoinera** [comment]
I will restart with this quite soon! I really like this feature

**Comment by Bitcoinera** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Why days are so short and human energy limited?

**Comment by jbibla** [comment]
let's close for now and revisit when the time is more appropriate

**Comment by Bitcoinera** [comment]
> let's close for now and revisit when the time is more appropriate

okiii

**Pull request closed without merging**
