### PR TITLE
Ana/4432 fix all session addresses invalid notification input

### LINKED ISSUE #4432: Variable $addressObjects got invalid value (NotificationInput)
Apparently, we changed how session are stored in store and now we are storing things such as icons, sessionTypes... which breaks the `notifications` query, since the `NotificationInput` can only contain `networkId` and `address`.

Opening here the issue to follow the procol.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4432 

**Description:**

Fixes this (further description in the issue):

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f030d9107eb21cb9398c4cc--lunieio.netlify.app

**Comment by faboweb** [comment]
e2e fails?

**Comment by Bitcoinera** [comment]
> e2e fails?

ah yes. There was something with the master account but I funded it already. Let's see

**Comment by Bitcoinera** [comment]
It passed the E2E :v:

**Pull request merged**
