### PR TITLE
Ana/reuse message creation file from app in api

### LINKED ISSUE #4879: Remove message creation in API and reuse message creation used in APP
api/lib/messageCreators...

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4879

**Description:**

Simple but effective refactor. One file and one folder less in API

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Review by faboweb — COMMENTED** [review]
You tested this? I thought some of the message creators were incompatible

**Comment by Bitcoinera** [comment]
> You tested this? I thought some of the message creators were incompatible

Tested with Cosmos Hub and Kusama and Polkadot

**Comment by faboweb** [comment]
oh, let's also cleanup and remove the files?

**Comment by Bitcoinera** [comment]
> oh, let's also cleanup and remove the files?

Thought I had done it? :eyes: Let me have a look

**Pull request merged**
